
package app.component.dialogMessage;

import app.controller.ClientController;
import app.controller.MaterielController;
import app.controller.RegisterController;
import app.model.ClientModel;
import app.model.InformationClient;
import app.model.InformationMateriel;
import app.model.InformationRegister;
import app.model.MaterielModel;
import app.model.RegisterModel;
import app.view.Dashboard;
import app.view.Register;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

public class DialogMessageWarning extends javax.swing.JDialog {

    /**
     * Creates new form DialogMessageWarning
     * @param parent
     * @param modal
     * @param message
     */
    public DialogMessageWarning(java.awt.Frame parent, boolean modal, String message) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        labelMessageAlert.setText(message);
    }
    
    /*public DialogMessageWarning(java.awt.Dialog parent, boolean modal, String message) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        labelMessageAlert.setText(message);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelMessageAlert = new javax.swing.JLabel();
        btnOui = new app.component.ButtonCustom();
        btnNon = new app.component.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon("src/app/images/computer-science.png").getImage());
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Projet L3\\DesktopAppVenteMaterielInformatique\\src\\app\\images\\warning.png")); // NOI18N

        labelMessageAlert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMessageAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessageAlert.setText("jLabel2");

        btnOui.setForeground(new java.awt.Color(255, 255, 255));
        btnOui.setText("OUI");
        btnOui.setBorderColor(new java.awt.Color(0, 51, 102));
        btnOui.setColor(new java.awt.Color(0, 51, 102));
        btnOui.setColorClick(new java.awt.Color(0, 51, 102));
        btnOui.setColorOver(new java.awt.Color(0, 153, 255));
        btnOui.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOuiActionPerformed(evt);
            }
        });

        btnNon.setBackground(new java.awt.Color(255, 102, 102));
        btnNon.setForeground(new java.awt.Color(255, 255, 255));
        btnNon.setText("NON");
        btnNon.setBorderColor(new java.awt.Color(255, 102, 102));
        btnNon.setColor(new java.awt.Color(255, 102, 102));
        btnNon.setColorClick(new java.awt.Color(255, 102, 102));
        btnNon.setColorOver(new java.awt.Color(255, 0, 0));
        btnNon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnOui, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnNon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelMessageAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(labelMessageAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOui, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonActionPerformed
        this.setVisible(false);
        
        InformationRegister register1 = new InformationRegister();
        RegisterModel modRegister = new RegisterModel();
        Register frmRegister = new Register();
        RegisterController registerController = new RegisterController(register1,modRegister,frmRegister);
        
        Dashboard dashboard = new Dashboard();
        InformationClient client = new InformationClient();
        ClientModel modClient = new ClientModel();
        ClientController ctrlClient = new ClientController(client,dashboard,modClient);
                
        InformationMateriel materiel = new InformationMateriel();
        MaterielModel modMat = new MaterielModel();
        MaterielController ctrlMateriel = new MaterielController(materiel,dashboard,modMat);
    }//GEN-LAST:event_btnNonActionPerformed

    private void btnOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOuiActionPerformed
        this.setVisible(false);
        
        InformationRegister register1 = new InformationRegister();
        RegisterModel modRegister = new RegisterModel();
        Register frmRegister = new Register();
        RegisterController registerController = new RegisterController(register1,modRegister,frmRegister);
        
        Dashboard dashboard = new Dashboard();
        InformationClient client = new InformationClient();
        ClientModel modClient = new ClientModel();
        ClientController ctrlClient = new ClientController(client,dashboard,modClient);
                
        InformationMateriel materiel = new InformationMateriel();
        MaterielModel modMat = new MaterielModel();
        MaterielController ctrlMateriel = new MaterielController(materiel,dashboard,modMat);
    }//GEN-LAST:event_btnOuiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogMessageWarning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogMessageWarning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogMessageWarning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogMessageWarning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogMessageWarning dialog = new DialogMessageWarning(new javax.swing.JFrame(), true ,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public app.component.ButtonCustom btnNon;
    public app.component.ButtonCustom btnOui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelMessageAlert;
    // End of variables declaration//GEN-END:variables
}
