package app.component;

import javax.swing.ImageIcon;


public class AchatEditCommande extends javax.swing.JDialog {

    /**
     * Creates new form AchatEditCommande
     * @param parent
     * @param modal
     * @param design
     * @param pu
     * @param stock
     * @param qte
     * @param row
     */
    public AchatEditCommande(java.awt.Dialog parent, boolean modal,String design, Double pu,int stock,int qte,int row) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        this.labelHiddenRow.setText(row + "");
        this.labelHiddenRow.setVisible(false);
        this.labelInfoDesignEdit.setText(design);
        this.labelInfoPUEdit.setText(pu + "");
        this.labelInfoStockEdit.setText(stock + "");
        this.inputValueQteEdit.setText(qte + "");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelInfoDesignEdit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelInfoStockEdit = new javax.swing.JLabel();
        inputValueQteEdit = new app.component.TextFieldCustom();
        btnModifyCommandeEdit = new app.component.ButtonCustom();
        btnAnnulerCommandeEdit = new app.component.ButtonCustom();
        labelInfoPUEdit = new javax.swing.JLabel();
        labelHiddenRow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new ImageIcon("src/app/images/computer-science.png").getImage());
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Prix unitaire");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Designation");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Qte");

        labelInfoDesignEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoDesignEdit.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoDesignEdit.setText("Designation");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Stock restant");

        labelInfoStockEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoStockEdit.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoStockEdit.setText("Stock restant");

        inputValueQteEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnModifyCommandeEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnModifyCommandeEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnModifyCommandeEdit.setText("MODIFIER");
        btnModifyCommandeEdit.setBorderColor(new java.awt.Color(0, 51, 102));
        btnModifyCommandeEdit.setBorderPainted(false);
        btnModifyCommandeEdit.setColor(new java.awt.Color(0, 51, 102));
        btnModifyCommandeEdit.setColorClick(new java.awt.Color(0, 51, 102));
        btnModifyCommandeEdit.setColorOver(new java.awt.Color(0, 153, 255));
        btnModifyCommandeEdit.setDefaultCapable(false);
        btnModifyCommandeEdit.setFocusPainted(false);
        btnModifyCommandeEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModifyCommandeEdit.setOpaque(true);
        btnModifyCommandeEdit.setRequestFocusEnabled(false);

        btnAnnulerCommandeEdit.setBackground(new java.awt.Color(102, 102, 102));
        btnAnnulerCommandeEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAnnulerCommandeEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnulerCommandeEdit.setText("ANNULER");
        btnAnnulerCommandeEdit.setBorderColor(new java.awt.Color(102, 102, 102));
        btnAnnulerCommandeEdit.setBorderPainted(false);
        btnAnnulerCommandeEdit.setColor(new java.awt.Color(102, 102, 102));
        btnAnnulerCommandeEdit.setColorClick(new java.awt.Color(102, 102, 102));
        btnAnnulerCommandeEdit.setColorOver(new java.awt.Color(255, 153, 153));
        btnAnnulerCommandeEdit.setDefaultCapable(false);
        btnAnnulerCommandeEdit.setFocusPainted(false);
        btnAnnulerCommandeEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnnulerCommandeEdit.setOpaque(true);
        btnAnnulerCommandeEdit.setRequestFocusEnabled(false);

        labelInfoPUEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoPUEdit.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoPUEdit.setText("Prix unitaire");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAnnulerCommandeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModifyCommandeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelInfoDesignEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelInfoPUEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelInfoStockEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(inputValueQteEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelHiddenRow, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelHiddenRow, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelInfoDesignEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInfoPUEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelInfoStockEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputValueQteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnulerCommandeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyCommandeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AchatEditCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AchatEditCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AchatEditCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AchatEditCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AchatEditCommande dialog = new AchatEditCommande(new javax.swing.JDialog(), true,null,null,0,0,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public app.component.ButtonCustom btnAnnulerCommandeEdit;
    public app.component.ButtonCustom btnModifyCommandeEdit;
    public app.component.TextFieldCustom inputValueQteEdit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelHiddenRow;
    public javax.swing.JLabel labelInfoDesignEdit;
    public javax.swing.JLabel labelInfoPUEdit;
    public javax.swing.JLabel labelInfoStockEdit;
    // End of variables declaration//GEN-END:variables
}
