package app.component;

import app.model.ConnexionDB;
import app.model.InformationClient;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import app.component.datechooser.EventDateChooser;
import app.component.datechooser.SelectedAction;
import app.component.datechooser.SelectedDate;
import app.model.AchatModel;
import app.model.InformationMateriel;
import app.model.MaterielModel;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;


public class AchatModalForm extends javax.swing.JDialog {
    
    public Double totalAchat = 0.0 ;

    /**
     * Creates new form AchatModalForm
     * @param parent
     * @param modal
     * @param client
     */
    public AchatModalForm(java.awt.Frame parent, boolean modal,InformationClient client) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
        this.labelNumCliCommande.setText(client.getNumCli());
        this.labelNomCliCommande.setText(client.getNomCli());
        this.labelAdrCliCommande.setText(client.getAdrCli());
        
        loadComboInformationMateriel();
        dateChooser.toDay();
      
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
        
        autoIDCommande(client);
        fixTable(jScrollPane2);
        
        tableCommande.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD, 12));
        tableCommande.getTableHeader().setForeground(Color.black);
        
        tableCommande.setRowHeight(30);
        
        btnAchatArticle.setVisible(false);
        
        btnEditAchatArticle.setVisible(false);
        btnValidateCommande.setVisible(false);
        labelMontantTotal.setVisible(false);
        labelMontantValue.setVisible(false);
        btnDeleteCommande.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new app.component.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNumCliCommande = new javax.swing.JLabel();
        labelNomCliCommande = new javax.swing.JLabel();
        labelAdrCliCommande = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAchatArticle = new app.component.ButtonCustom();
        txtPUArticle = new app.component.TextFieldCustom();
        txtQteArticle = new app.component.TextFieldCustom();
        txtStockRestantArticle = new app.component.TextFieldCustom();
        jLabel13 = new javax.swing.JLabel();
        comboArticleSearch = new app.component.comboSuggestion.ComboBoxSuggestion();
        btnSeeArctileSearch = new app.component.ButtonCustom();
        jPanel5 = new javax.swing.JPanel();
        btnValidateCommande = new app.component.ButtonCustom();
        labelMontantTotal = new javax.swing.JLabel();
        btnEditAchatArticle = new app.component.ButtonCustom();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCommande = new javax.swing.JTable();
        labelMontantValue = new javax.swing.JLabel();
        btnDeleteCommande = new app.component.ButtonCustom();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelNumCommande = new javax.swing.JLabel();
        dateChooserCommande = new app.component.TextFieldCustom();
        btnSeeDateChooser = new app.component.ButtonCustom();
        btnCloseAchat = new app.component.ButtonCustom();

        dateChooser.setTextRefernce(dateChooserCommande);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new ImageIcon("src/app/images/computer-science.png").getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1045, 616));
        jPanel1.setMinimumSize(new java.awt.Dimension(1045, 616));
        jPanel1.setPreferredSize(new java.awt.Dimension(1045, 616));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Numéro du client");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 114, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Nom du client");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 102, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Adresse du client");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 102, -1));

        labelNumCliCommande.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNumCliCommande.setText("jLabel14");
        jPanel2.add(labelNumCliCommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 170, 30));

        labelNomCliCommande.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNomCliCommande.setText("jLabel15");
        jPanel2.add(labelNomCliCommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, 30));

        labelAdrCliCommande.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAdrCliCommande.setText("jLabel16");
        jPanel2.add(labelAdrCliCommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Information du client");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Stock restant");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 90, 24));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Article");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 24));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Quantité");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 20));

        btnAchatArticle.setBackground(new java.awt.Color(0, 153, 255));
        btnAchatArticle.setBorder(null);
        btnAchatArticle.setForeground(new java.awt.Color(255, 255, 255));
        btnAchatArticle.setText(" >>>");
        btnAchatArticle.setBorderColor(new java.awt.Color(153, 153, 153));
        btnAchatArticle.setBorderPainted(false);
        btnAchatArticle.setColor(new java.awt.Color(0, 153, 255));
        btnAchatArticle.setColorClick(new java.awt.Color(0, 153, 255));
        btnAchatArticle.setColorOver(new java.awt.Color(0, 51, 102));
        btnAchatArticle.setFocusPainted(false);
        btnAchatArticle.setFocusable(false);
        btnAchatArticle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAchatArticle.setOpaque(true);
        jPanel4.add(btnAchatArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 90, 50));

        txtPUArticle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPUArticle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPUArticle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPUArticle.setEnabled(false);
        txtPUArticle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtPUArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 40));

        txtQteArticle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtQteArticle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(txtQteArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 40));

        txtStockRestantArticle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtStockRestantArticle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStockRestantArticle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtStockRestantArticle.setEnabled(false);
        txtStockRestantArticle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtStockRestantArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Prix unitaire");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 24));

        comboArticleSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboArticleSearchItemStateChanged(evt);
            }
        });
        jPanel4.add(comboArticleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 40));

        btnSeeArctileSearch.setBorder(null);
        btnSeeArctileSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSeeArctileSearch.setText("...");
        btnSeeArctileSearch.setBorderColor(new java.awt.Color(0, 51, 102));
        btnSeeArctileSearch.setColor(new java.awt.Color(0, 51, 102));
        btnSeeArctileSearch.setColorClick(new java.awt.Color(153, 153, 153));
        btnSeeArctileSearch.setColorOver(new java.awt.Color(255, 204, 204));
        btnSeeArctileSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeeArctileSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSeeArctileSearch.setOpaque(true);
        jPanel4.add(btnSeeArctileSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 40, 40));

        jPanel5.setBackground(new java.awt.Color(220, 220, 220));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnValidateCommande.setBorder(null);
        btnValidateCommande.setForeground(new java.awt.Color(255, 255, 255));
        btnValidateCommande.setText("ENREGISTRER");
        btnValidateCommande.setBorderColor(new java.awt.Color(153, 153, 153));
        btnValidateCommande.setBorderPainted(false);
        btnValidateCommande.setColor(new java.awt.Color(0, 153, 255));
        btnValidateCommande.setColorClick(new java.awt.Color(0, 153, 255));
        btnValidateCommande.setColorOver(new java.awt.Color(0, 51, 102));
        btnValidateCommande.setFocusPainted(false);
        btnValidateCommande.setFocusable(false);
        btnValidateCommande.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnValidateCommande.setOpaque(true);
        jPanel5.add(btnValidateCommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 187, 50));

        labelMontantTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelMontantTotal.setText("Montant total");
        jPanel5.add(labelMontantTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 130, 20));

        btnEditAchatArticle.setBackground(new java.awt.Color(0, 255, 255));
        btnEditAchatArticle.setBorder(null);
        btnEditAchatArticle.setForeground(new java.awt.Color(255, 255, 255));
        btnEditAchatArticle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/edit.png"))); // NOI18N
        btnEditAchatArticle.setBorderColor(new java.awt.Color(0, 255, 255));
        btnEditAchatArticle.setBorderPainted(false);
        btnEditAchatArticle.setColor(new java.awt.Color(0, 255, 255));
        btnEditAchatArticle.setColorClick(new java.awt.Color(0, 255, 255));
        btnEditAchatArticle.setColorOver(new java.awt.Color(0, 51, 102));
        btnEditAchatArticle.setDefaultCapable(false);
        btnEditAchatArticle.setFocusPainted(false);
        btnEditAchatArticle.setFocusable(false);
        btnEditAchatArticle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditAchatArticle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditAchatArticle.setOpaque(true);
        btnEditAchatArticle.setRequestFocusEnabled(false);
        jPanel5.add(btnEditAchatArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 60, 50));

        tableCommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Désignation", "PU", "Quantité", "Montant"
            }
        ));
        tableCommande.setEditingColumn(0);
        tableCommande.setEditingRow(0);
        tableCommande.setFocusable(false);
        tableCommande.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableCommande.setRequestFocusEnabled(false);
        tableCommande.setRowHeight(35);
        tableCommande.getTableHeader().setReorderingAllowed(false);
        tableCommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCommandeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCommande);
        if (tableCommande.getColumnModel().getColumnCount() > 0) {
            tableCommande.getColumnModel().getColumn(2).setMinWidth(80);
            tableCommande.getColumnModel().getColumn(2).setPreferredWidth(80);
            tableCommande.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 430));

        labelMontantValue.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        labelMontantValue.setForeground(new java.awt.Color(255, 51, 51));
        labelMontantValue.setText("jLabel5");
        jPanel5.add(labelMontantValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 160, 40));

        btnDeleteCommande.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteCommande.setBorder(null);
        btnDeleteCommande.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCommande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/trash-bin.png"))); // NOI18N
        btnDeleteCommande.setBorderColor(new java.awt.Color(255, 51, 51));
        btnDeleteCommande.setBorderPainted(false);
        btnDeleteCommande.setColor(new java.awt.Color(255, 51, 51));
        btnDeleteCommande.setColorClick(new java.awt.Color(255, 51, 51));
        btnDeleteCommande.setColorOver(new java.awt.Color(255, 102, 102));
        btnDeleteCommande.setDefaultCapable(false);
        btnDeleteCommande.setFocusPainted(false);
        btnDeleteCommande.setFocusable(false);
        btnDeleteCommande.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteCommande.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteCommande.setOpaque(true);
        btnDeleteCommande.setRequestFocusEnabled(false);
        jPanel5.add(btnDeleteCommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 60, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Détails de la commande");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Information sur la commande");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Numéro du commande ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 147, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Date du commande");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 121, 30));

        labelNumCommande.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNumCommande.setText("jLabel17");
        jPanel3.add(labelNumCommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 110, 30));

        dateChooserCommande.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateChooserCommande.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jPanel3.add(dateChooserCommande, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, 30));

        btnSeeDateChooser.setBorder(null);
        btnSeeDateChooser.setForeground(new java.awt.Color(255, 255, 255));
        btnSeeDateChooser.setText("...");
        btnSeeDateChooser.setBorderColor(new java.awt.Color(0, 51, 102));
        btnSeeDateChooser.setColor(new java.awt.Color(0, 51, 102));
        btnSeeDateChooser.setColorClick(new java.awt.Color(153, 153, 153));
        btnSeeDateChooser.setColorOver(new java.awt.Color(255, 204, 204));
        btnSeeDateChooser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeeDateChooser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSeeDateChooser.setOpaque(true);
        btnSeeDateChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeDateChooserActionPerformed(evt);
            }
        });
        jPanel3.add(btnSeeDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 40, 30));

        btnCloseAchat.setBackground(new java.awt.Color(255, 51, 51));
        btnCloseAchat.setBorder(null);
        btnCloseAchat.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseAchat.setText("ANNULER");
        btnCloseAchat.setBorderColor(new java.awt.Color(255, 51, 51));
        btnCloseAchat.setColor(new java.awt.Color(255, 51, 51));
        btnCloseAchat.setColorClick(new java.awt.Color(255, 51, 51));
        btnCloseAchat.setColorOver(new java.awt.Color(255, 153, 153));
        btnCloseAchat.setFocusPainted(false);
        btnCloseAchat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCloseAchat.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCloseAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCloseAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fixTable(JScrollPane scroll) {
        scroll.setVerticalScrollBar(new app.component.tableCustom.ScrollBarCustom());
        JPanel panel = new JPanel();
        panel.setBackground(new Color(240, 240, 240));
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, panel);
        scroll.getViewport().setBackground(new Color(240, 240, 240));
        scroll.setBorder(BorderFactory.createLineBorder(new Color(240, 240, 240), 2));
    }
    
    private void btnSeeDateChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeDateChooserActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_btnSeeDateChooserActionPerformed

    private void tableCommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCommandeMouseClicked

        /*int row = tableCommande.getSelectedRow();

        String numCli = tableCommande.getValueAt(row, 0).toString();
        String nomCli = tableCommande.getValueAt(row, 1).toString();
        String adrCli = tableCommande.getValueAt(row, 2).toString();

        txtNumCliClient.setText(numCli);
        txtNomCliClient.setText(nomCli);
        txtAdresseCliClient.setText(adrCli);

        paneInfoClient.removeAll();
        paneInfoClient.add(paneModifyClient);
        paneInfoClient.repaint();
        paneInfoClient.revalidate();

        btnSearchNomClientAchat.setVisible(true);
        btnDeleteClient.setVisible(true);
        btnAddClientIcon.setVisible(true);*/
    }//GEN-LAST:event_tableCommandeMouseClicked

    private void comboArticleSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboArticleSearchItemStateChanged
        txtPUArticle.setText(null);
        txtQteArticle.setText(null);
        txtStockRestantArticle.setText(null);
    }//GEN-LAST:event_comboArticleSearchItemStateChanged

    
    public void autoIDCommande(InformationClient client){
        AchatModel modAchat = new AchatModel();
        
        ConnexionDB conn = new ConnexionDB();
        Connection connexion = conn.getConnexion(); 
        ResultSet rs = null;
     
        String sql = "SELECT MAX(NumFact) FROM achat WHERE NumClient = ?";
        
        try{
           
            int numRowCount = modAchat.listerNumClient().size();
            Object[] columns = new Object[numRowCount];
            boolean trouve = false;
            
            if(numRowCount == 0){
                 labelNumCommande.setText("FFT0001");
            }else{
                for(int i = 0; i < numRowCount ; i++){
                    columns[i] =  modAchat.listerNumClient().get(i).getNumCli();
                    String numero = columns[i]+"";
                    if(numero.equals(client.getNumCli())){
                        trouve = true;
                    }
                }
                
                if(trouve == true){
                    PreparedStatement ps = connexion.prepareStatement(sql);
                    ps.setString(1,client.getNumCli());
                    rs = ps.executeQuery();
                    rs.next();
                    rs.getString("MAX(NumFact)");

                    Long id = Long.parseLong(rs.getString("MAX(NumFact)").substring(3,rs.getString("MAX(NumFact)").length()));
                    id++;
                    labelNumCommande.setText("FFT" + String.format("%04d", id));            
                }else{
                    labelNumCommande.setText("FFT0001");    
                }
                /*int j = 0;
                
                while(j < numRowCount && trouve == false){
                    
                    if(client.getNumCli().equals(columns[j])){
                        trouve = true;
                    }
                    
                    j++;
                }*/
            }

        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    public void loadComboInformationMateriel(){
        comboArticleSearch.removeAllItems();
        MaterielModel modMat = new MaterielModel();
        
        int numRowCount = modMat.listerMateriel().size();
        
        for(int i = 0; i < numRowCount ; i++){
            String design = modMat.listerMateriel().get(i).getDesign();
            this.comboArticleSearch.addItem(design);
 
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AchatModalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AchatModalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AchatModalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AchatModalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AchatModalForm dialog = new AchatModalForm(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public app.component.ButtonCustom btnAchatArticle;
    public app.component.ButtonCustom btnCloseAchat;
    public app.component.ButtonCustom btnDeleteCommande;
    public app.component.ButtonCustom btnEditAchatArticle;
    public app.component.ButtonCustom btnSeeArctileSearch;
    public app.component.ButtonCustom btnSeeDateChooser;
    public app.component.ButtonCustom btnValidateCommande;
    public app.component.comboSuggestion.ComboBoxSuggestion comboArticleSearch;
    private app.component.datechooser.DateChooser dateChooser;
    public app.component.TextFieldCustom dateChooserCommande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labelAdrCliCommande;
    public javax.swing.JLabel labelMontantTotal;
    public javax.swing.JLabel labelMontantValue;
    public javax.swing.JLabel labelNomCliCommande;
    public javax.swing.JLabel labelNumCliCommande;
    public javax.swing.JLabel labelNumCommande;
    public javax.swing.JTable tableCommande;
    public app.component.TextFieldCustom txtPUArticle;
    public app.component.TextFieldCustom txtQteArticle;
    public app.component.TextFieldCustom txtStockRestantArticle;
    // End of variables declaration//GEN-END:variables
}
