package app.component;

import app.controller.AchatController;
import static app.controller.CommandeController.conversionDates;
import app.model.AchatModel;
import app.model.ConnexionDB;
import app.model.InformationAchat;
import app.model.InformationClient;
import app.model.InformationMateriel;
import app.view.Dashboard;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AchatModifyAchat extends javax.swing.JDialog {

    
    
    public AchatModifyAchat(java.awt.Frame parent, boolean modal,InformationClient client,InformationMateriel materiel, InformationAchat achat,int row) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.labelInfoDesignEdit.setText(materiel.getDesign());
        this.labelInfoPUEdit.setText(materiel.getPrixU() + "");
        this.labelInfoStockEdit.setText(materiel.getStock() +"");
        this.inputValueQteEdit.setText(achat.getQte() + "");
        this.labelInfoStockEdit3.setText(achat.getDateAchat() + "");
        this.labelInfoDesignEdit1.setText(client.getNumCli());
        this.labelInfoPUEdit1.setText(client.getNomCli());
        this.labelInfoStockEdit2.setText(achat.getNumMat());
        this.labelInfoStockEdit4.setText(materiel.getNumMateriel());
        this.labelHiddenRow.setText(row+"");
        this.labelHiddenRow.setVisible(false);
        this.labelHiddenRow1.setVisible(false);
        this.labelHiddenRow1.setText(achat.getQte() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelInfoDesignEdit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelInfoStockEdit = new javax.swing.JLabel();
        inputValueQteEdit = new app.component.TextFieldCustom();
        btnModifyCommandeEdit1 = new app.component.ButtonCustom();
        btnAnnulerCommandeEdit1 = new app.component.ButtonCustom();
        labelInfoPUEdit = new javax.swing.JLabel();
        labelHiddenRow = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelInfoDesignEdit1 = new javax.swing.JLabel();
        labelInfoPUEdit1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelInfoStockEdit2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelInfoStockEdit3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelInfoStockEdit4 = new javax.swing.JLabel();
        labelHiddenRow1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon("src/app/images/computer-science.png").getImage());
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Prix unitaire");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Designation");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Qte");

        labelInfoDesignEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoDesignEdit.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoDesignEdit.setText("Designation");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Stock restant");

        labelInfoStockEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoStockEdit.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoStockEdit.setText("Stock restant");

        inputValueQteEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnModifyCommandeEdit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnModifyCommandeEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnModifyCommandeEdit1.setText("MODIFIER");
        btnModifyCommandeEdit1.setBorderColor(new java.awt.Color(0, 51, 102));
        btnModifyCommandeEdit1.setBorderPainted(false);
        btnModifyCommandeEdit1.setColor(new java.awt.Color(0, 51, 102));
        btnModifyCommandeEdit1.setColorClick(new java.awt.Color(0, 51, 102));
        btnModifyCommandeEdit1.setColorOver(new java.awt.Color(0, 153, 255));
        btnModifyCommandeEdit1.setDefaultCapable(false);
        btnModifyCommandeEdit1.setFocusPainted(false);
        btnModifyCommandeEdit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModifyCommandeEdit1.setOpaque(true);
        btnModifyCommandeEdit1.setRequestFocusEnabled(false);

        btnAnnulerCommandeEdit1.setBackground(new java.awt.Color(102, 102, 102));
        btnAnnulerCommandeEdit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAnnulerCommandeEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnulerCommandeEdit1.setText("ANNULER");
        btnAnnulerCommandeEdit1.setBorderColor(new java.awt.Color(102, 102, 102));
        btnAnnulerCommandeEdit1.setBorderPainted(false);
        btnAnnulerCommandeEdit1.setColor(new java.awt.Color(102, 102, 102));
        btnAnnulerCommandeEdit1.setColorClick(new java.awt.Color(102, 102, 102));
        btnAnnulerCommandeEdit1.setColorOver(new java.awt.Color(255, 153, 153));
        btnAnnulerCommandeEdit1.setDefaultCapable(false);
        btnAnnulerCommandeEdit1.setFocusPainted(false);
        btnAnnulerCommandeEdit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnnulerCommandeEdit1.setOpaque(true);
        btnAnnulerCommandeEdit1.setRequestFocusEnabled(false);

        labelInfoPUEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoPUEdit.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoPUEdit.setText("Prix unitaire");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("N° Client");

        labelInfoDesignEdit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoDesignEdit1.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoDesignEdit1.setText("Designation");

        labelInfoPUEdit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoPUEdit1.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoPUEdit1.setText("Prix unitaire");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Nom du client");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("N° Facture");

        labelInfoStockEdit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoStockEdit2.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoStockEdit2.setText("Stock restant");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Date");

        labelInfoStockEdit3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoStockEdit3.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoStockEdit3.setText("Date");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("N° Materiel");

        labelInfoStockEdit4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoStockEdit4.setForeground(new java.awt.Color(0, 0, 255));
        labelInfoStockEdit4.setText("Stock restant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(inputValueQteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelInfoStockEdit3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelInfoStockEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelInfoPUEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelInfoStockEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelInfoDesignEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHiddenRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addComponent(labelHiddenRow, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(67, 67, 67)
                        .addComponent(labelInfoStockEdit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnnulerCommandeEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btnModifyCommandeEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelInfoPUEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(79, 79, 79))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelInfoDesignEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(labelInfoStockEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHiddenRow, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHiddenRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(labelInfoStockEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(labelInfoDesignEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(labelInfoDesignEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInfoPUEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInfoPUEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labelInfoStockEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnnulerCommandeEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifyCommandeEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputValueQteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInfoStockEdit3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AchatModifyAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AchatModifyAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AchatModifyAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AchatModifyAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AchatModifyAchat dialog = new AchatModifyAchat(new javax.swing.JFrame(), true,null,null,null,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public app.component.ButtonCustom btnAnnulerCommandeEdit1;
    public app.component.ButtonCustom btnModifyCommandeEdit1;
    public app.component.TextFieldCustom inputValueQteEdit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelHiddenRow;
    public javax.swing.JLabel labelHiddenRow1;
    public javax.swing.JLabel labelInfoDesignEdit;
    public javax.swing.JLabel labelInfoDesignEdit1;
    public javax.swing.JLabel labelInfoPUEdit;
    public javax.swing.JLabel labelInfoPUEdit1;
    public javax.swing.JLabel labelInfoStockEdit;
    public javax.swing.JLabel labelInfoStockEdit2;
    public javax.swing.JLabel labelInfoStockEdit3;
    public javax.swing.JLabel labelInfoStockEdit4;
    // End of variables declaration//GEN-END:variables
}
