package app.view;

import app.controller.ClientController;
import app.controller.RegisterController;
import app.model.ClientModel;
import app.model.InformationClient;
import app.model.InformationRegister;
import app.model.RegisterModel;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.ImageIcon;


public class Login extends javax.swing.JFrame {
    
     /*InformationRegister register = new InformationRegister();
    LoginModel modLogin = new LoginModel();
    Login frmLogin = new Login();
    LoginController loginController = new LoginController(register,modLogin,frmLogin);*/
    
    public Login() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setSize(380,500);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        icon_minimizeLogin = new javax.swing.JLabel();
        icon_closeLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_username_login = new app.component.TextFieldCustom();
        txt_password_login = new app.component.PasswordFieldCustom();
        checkPasswordLogin = new app.component.CheckBoxCustom();
        btn_connect_login = new app.component.ButtonCustom();
        jLabel8 = new javax.swing.JLabel();
        btn_createAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("src/app/images/computer-science.png").getImage());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_minimizeLogin.setBackground(new java.awt.Color(153, 204, 255));
        icon_minimizeLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_minimizeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/minus(1).png"))); // NOI18N
        icon_minimizeLogin.setOpaque(true);
        icon_minimizeLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_minimizeLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_minimizeLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_minimizeLoginMouseExited(evt);
            }
        });
        jPanel2.add(icon_minimizeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 30));

        icon_closeLogin.setBackground(new java.awt.Color(153, 204, 255));
        icon_closeLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_closeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/cancel.png"))); // NOI18N
        icon_closeLogin.setOpaque(true);
        icon_closeLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_closeLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_closeLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_closeLoginMouseExited(evt);
            }
        });
        jPanel2.add(icon_closeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/technology.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Technology Business");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 20));

        jLabel4.setFont(new java.awt.Font("MV Boli", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Future Tech");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nom de l'utilisateur");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Mot de passe");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        txt_username_login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_username_login.setOpaque(false);
        jPanel1.add(txt_username_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 290, 30));

        txt_password_login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_password_login.setOpaque(false);
        jPanel1.add(txt_password_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 290, 30));

        checkPasswordLogin.setBackground(new java.awt.Color(0, 51, 102));
        checkPasswordLogin.setForeground(new java.awt.Color(153, 153, 153));
        checkPasswordLogin.setText(" Afficher le mot de passe");
        checkPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPasswordLoginActionPerformed(evt);
            }
        });
        jPanel1.add(checkPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        btn_connect_login.setBackground(new java.awt.Color(153, 204, 255));
        btn_connect_login.setBorder(null);
        btn_connect_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_connect_login.setText("CONNECTER");
        btn_connect_login.setBorderColor(new java.awt.Color(153, 204, 255));
        btn_connect_login.setColor(new java.awt.Color(153, 204, 255));
        btn_connect_login.setColorClick(new java.awt.Color(153, 204, 255));
        btn_connect_login.setColorOver(new java.awt.Color(0, 51, 102));
        btn_connect_login.setFocusPainted(false);
        btn_connect_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_connect_login.setOver(true);
        btn_connect_login.setRadius(25);
        jPanel1.add(btn_connect_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 190, 40));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Vous n'avez pas de compte?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, 30));

        btn_createAccount.setBackground(new java.awt.Color(255, 255, 255));
        btn_createAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_createAccount.setForeground(new java.awt.Color(0, 102, 255));
        btn_createAccount.setText("Créer un compte");
        btn_createAccount.setOpaque(true);
        btn_createAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_createAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_createAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_createAccountMouseExited(evt);
            }
        });
        jPanel1.add(btn_createAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPasswordLoginActionPerformed
        if(checkPasswordLogin.isSelected()){
            txt_password_login.setEchoChar((char)0);
        }else{
            txt_password_login.setEchoChar('*');
        }
    }//GEN-LAST:event_checkPasswordLoginActionPerformed

    private void icon_minimizeLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeLoginMouseClicked
        icon_minimizeLogin.setBackground(new Color(153,153,153));
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_icon_minimizeLoginMouseClicked

    private void icon_minimizeLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeLoginMouseEntered
        icon_minimizeLogin.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_icon_minimizeLoginMouseEntered

    private void icon_minimizeLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeLoginMouseExited
        icon_minimizeLogin.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_icon_minimizeLoginMouseExited

    private void icon_closeLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeLoginMouseClicked
        icon_closeLogin.setBackground(new Color(255,204,204));
        System.exit(0);
    }//GEN-LAST:event_icon_closeLoginMouseClicked

    private void icon_closeLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeLoginMouseEntered
        icon_closeLogin.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_icon_closeLoginMouseEntered

    private void icon_closeLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeLoginMouseExited
        icon_closeLogin.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_icon_closeLoginMouseExited

    private void btn_createAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createAccountMouseEntered
        btn_createAccount.setForeground(new Color(204,0,204));
    }//GEN-LAST:event_btn_createAccountMouseEntered

    private void btn_createAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createAccountMouseExited
       btn_createAccount.setForeground(new Color(0,102,255));
    }//GEN-LAST:event_btn_createAccountMouseExited

    private void btn_createAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createAccountMouseClicked
        

        InformationRegister register1 = new InformationRegister();
        RegisterModel modRegister = new RegisterModel();
        Register frmRegister = new Register();
        RegisterController registerController = new RegisterController(register1,modRegister,frmRegister);
    
        frmRegister.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_createAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public app.component.ButtonCustom btn_connect_login;
    private javax.swing.JLabel btn_createAccount;
    private app.component.CheckBoxCustom checkPasswordLogin;
    private javax.swing.JLabel icon_closeLogin;
    private javax.swing.JLabel icon_minimizeLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public app.component.PasswordFieldCustom txt_password_login;
    public app.component.TextFieldCustom txt_username_login;
    // End of variables declaration//GEN-END:variables
}
