package app.view;

import app.controller.LoginController;
import app.model.InformationRegister;
import app.model.LoginModel;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.ImageIcon;

public class Register extends javax.swing.JFrame {
    
    /*InformationRegister register = new InformationRegister();
    RegisterModel modRegister = new RegisterModel();
    Register frmRegister = new Register();
    RegisterController registerController = new RegisterController(register,modRegister,frmRegister); */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(380, 532);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        icon_minimizeRegister = new javax.swing.JLabel();
        icon_closeRegister = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_username_register = new app.component.TextFieldCustom();
        txt_password_register = new app.component.PasswordFieldCustom();
        txt_passwordConfirm_register = new app.component.PasswordFieldCustom();
        checkPasswordRegister = new app.component.CheckBoxCustom();
        checkPasswordConfirm = new app.component.CheckBoxCustom();
        btn_save_register = new app.component.ButtonCustom();
        btn_returnRegister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("src/app/images/computer-science.png").getImage());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_minimizeRegister.setBackground(new java.awt.Color(153, 204, 255));
        icon_minimizeRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_minimizeRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/minus(1).png"))); // NOI18N
        icon_minimizeRegister.setOpaque(true);
        icon_minimizeRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_minimizeRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_minimizeRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_minimizeRegisterMouseExited(evt);
            }
        });
        jPanel2.add(icon_minimizeRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 30));

        icon_closeRegister.setBackground(new java.awt.Color(153, 204, 255));
        icon_closeRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_closeRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/cancel.png"))); // NOI18N
        icon_closeRegister.setOpaque(true);
        icon_closeRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_closeRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_closeRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_closeRegisterMouseExited(evt);
            }
        });
        jPanel2.add(icon_closeRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/technology.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("MV Boli", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Future Tech");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 130, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Technology Business");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nom de l'utilisateur");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Mot de passe");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Confirmer le mot de passe");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txt_username_register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_username_register.setOpaque(false);
        jPanel1.add(txt_username_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 290, 30));

        txt_password_register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_password_register.setOpaque(false);
        jPanel1.add(txt_password_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 290, 30));

        txt_passwordConfirm_register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_passwordConfirm_register.setOpaque(false);
        jPanel1.add(txt_passwordConfirm_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 290, 30));

        checkPasswordRegister.setBackground(new java.awt.Color(0, 51, 102));
        checkPasswordRegister.setForeground(new java.awt.Color(153, 153, 153));
        checkPasswordRegister.setText(" Afficher le mot de passe");
        checkPasswordRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPasswordRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(checkPasswordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        checkPasswordConfirm.setBackground(new java.awt.Color(0, 51, 102));
        checkPasswordConfirm.setForeground(new java.awt.Color(153, 153, 153));
        checkPasswordConfirm.setText(" Afficher le mot de passe");
        checkPasswordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPasswordConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(checkPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        btn_save_register.setBackground(new java.awt.Color(153, 204, 255));
        btn_save_register.setBorder(null);
        btn_save_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_save_register.setText("ENREGISTRER");
        btn_save_register.setBorderColor(new java.awt.Color(153, 204, 255));
        btn_save_register.setColor(new java.awt.Color(153, 204, 255));
        btn_save_register.setColorClick(new java.awt.Color(153, 204, 255));
        btn_save_register.setColorOver(new java.awt.Color(0, 51, 102));
        btn_save_register.setFocusPainted(false);
        btn_save_register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save_register.setOver(true);
        btn_save_register.setRadius(25);
        jPanel1.add(btn_save_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 190, 40));

        btn_returnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_returnRegister.setForeground(new java.awt.Color(255, 153, 153));
        btn_returnRegister.setText("<<<<");
        btn_returnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_returnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_returnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_returnRegisterMouseExited(evt);
            }
        });
        jPanel1.add(btn_returnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkPasswordRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPasswordRegisterActionPerformed
        if(checkPasswordRegister.isSelected()){
            txt_password_register.setEchoChar((char)0);
        }else{
            txt_password_register.setEchoChar('*');
        }
    }//GEN-LAST:event_checkPasswordRegisterActionPerformed

    private void icon_minimizeRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeRegisterMouseClicked
        icon_minimizeRegister.setBackground(new Color(153,153,153));
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_icon_minimizeRegisterMouseClicked

    private void icon_minimizeRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeRegisterMouseEntered
        icon_minimizeRegister.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_icon_minimizeRegisterMouseEntered

    private void icon_minimizeRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizeRegisterMouseExited
        icon_minimizeRegister.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_icon_minimizeRegisterMouseExited

    private void icon_closeRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeRegisterMouseClicked
       icon_closeRegister.setBackground(new Color(255,204,204));
        System.exit(0);
    }//GEN-LAST:event_icon_closeRegisterMouseClicked

    private void icon_closeRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeRegisterMouseEntered
      icon_closeRegister.setBackground(new Color(255,204,204));
    }//GEN-LAST:event_icon_closeRegisterMouseEntered

    private void icon_closeRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeRegisterMouseExited
        icon_closeRegister.setBackground(new Color(153,204,255));
    }//GEN-LAST:event_icon_closeRegisterMouseExited

    private void btn_returnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnRegisterMouseEntered
       btn_returnRegister.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_btn_returnRegisterMouseEntered

    private void btn_returnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnRegisterMouseExited
       btn_returnRegister.setForeground(new Color(255,153,153));
    }//GEN-LAST:event_btn_returnRegisterMouseExited

    private void btn_returnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnRegisterMouseClicked
        Login login = new Login();
        
        InformationRegister register = new InformationRegister();
        LoginModel modLogin = new LoginModel();
        Login frmLogin = new Login();
        LoginController loginController = new LoginController(register,modLogin,frmLogin);
        
        login.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_returnRegisterMouseClicked

    private void checkPasswordConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPasswordConfirmActionPerformed
        if(checkPasswordConfirm.isSelected()){
            txt_passwordConfirm_register.setEchoChar((char)0);
        }else{
            txt_passwordConfirm_register.setEchoChar('*');
        }
    }//GEN-LAST:event_checkPasswordConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_returnRegister;
    public app.component.ButtonCustom btn_save_register;
    private app.component.CheckBoxCustom checkPasswordConfirm;
    private app.component.CheckBoxCustom checkPasswordRegister;
    private javax.swing.JLabel icon_closeRegister;
    private javax.swing.JLabel icon_minimizeRegister;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public app.component.PasswordFieldCustom txt_passwordConfirm_register;
    public app.component.PasswordFieldCustom txt_password_register;
    public app.component.TextFieldCustom txt_username_register;
    // End of variables declaration//GEN-END:variables
}
